name: pipelineWebPre
#on:
#   workflow_dispatch:

on:
  pull_request:
    branches:
      - preproduccion
    types:
      - closed  

jobs:
  deploy_to_preproduction:
    runs-on: self-hosted
    environment: Preproduccion

    outputs:
         GROUP_OUT: ${{ steps.var_setup.outputs.GROUP_ID }}
         ARTIFACT_OUT: ${{ steps.var_setup.outputs.ARTIFACT_ID }}
         VERSION_OUT: ${{ steps.var_setup.outputs.VERSION }}
         NAME_OUT: ${{ steps.var_setup.outputs.NAME_ID }}
         BRANCH_OUT: ${{ steps.var_setup.outputs.BRANCH_NAME }}
         REPOSITORY_OUT: ${{ steps.var_setup.outputs.REPOSITORY_NAME }}
         #NEWVERSION: ${{ steps.version-plus.outputs.NEWVERSION }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # - name: Check if PR is merged and approved
      #   id: check_approval
      #   run: |
      #     echo "Checking if PR is merged and approved..."
      #     if [[ ${{ github.event_name }} == 'pull_request' && ${{ github.event.pull_request.merged }} == true && ${{ github.event.pull_request.base.ref }} == 'preproduccion' ]]; then
      #       echo "PR aceptado hacia la rama de preproduccion."
      #       echo "approved=true" >> $GITHUB_OUTPUT
      #       echo "approved=true" >> $GITHUB_ENV
      #     else
      #       echo "PR no es aceptado hacia la rama de preproduccion. Contacte al equipo de Liberaciones para indicaciones."
      #       echo "approved=false" >> $GITHUB_OUTPUT
      #       echo "approved=false" >> $GITHUB_ENV
      #     fi

      - name: read_pom_xml and setting variables
        id: var_setup
       # if: steps.check_approval.outputs.approved == 'true'
        run: |
          # USE GREP TO EXTRACT THE LINE WE NEED. SELECT SECOND OCCURENCE WITH SED. THEN CLEAN HTML TAGS WITH SED
          GROUP_ID_LOCAL=$(grep -m2 "<groupId>" ./pom.xml | sed -n 2p | sed 's/^.<groupId>//' | sed 's/<\/groupId>.$//')
          ARTIFACT_ID_PRE=$(grep -m2 "<artifactId>" ./pom.xml |  sed -n 2p | sed 's/^.<artifactId>//' | sed 's/<\/artifactId>.$//')
          VERSION_LOCAL=$(grep -m2 "<version>" ./pom.xml |  sed -n 2p | sed 's/^.<version>//' | sed 's/<\/version>.$//')
          ARTIFACT_ID_LOCAL="${ARTIFACT_ID_PRE}-presentacion"
          NAME_LOCAL="${ARTIFACT_ID_LOCAL}-${VERSION_LOCAL}.war"
          REPOSITORY_NAME=$(echo "${GITHUB_REPOSITORY}" | sed 's/.*\///')
          
          #se utilizaria cuando haga el pull request approval exclusivamente, caso contrario, debe estar en comentario
          BRANCH_LOCAL=$(echo "${{ github.event.pull_request.head.ref }}")  
          
          #se utiliza github_ref_name en ejecucion con workflow_dispatch, no usar en build y deploy con pull request
          #BRANCH_LOCAL=$(echo "${GITHUB_REF_NAME}")  
          
          echo "GroupID=$GROUP_ID_LOCAL and more"
          echo "ArtifactID=$ARTIFACT_ID_LOCAL and more"
          echo "Version=$VERSION_LOCAL and more"
          echo "Name = $NAME_LOCAL"
          echo "Branch = $BRANCH_LOCAL"
          echo "RepositoryName = $REPOSITORY_NAME"
          
          # SET VARIABLES TO GITHUB_ENVIRONMENT AND OUTPUT
          echo "GROUP_ID=$(echo $GROUP_ID_LOCAL)" >> $GITHUB_OUTPUT
          echo "GROUP_ID=$(echo $GROUP_ID_LOCAL)" >> $GITHUB_ENV
          echo "ARTIFACT_ID=$(echo $ARTIFACT_ID_LOCAL)" >> $GITHUB_OUTPUT
          echo "ARTIFACT_ID=$(echo $ARTIFACT_ID_LOCAL)" >> $GITHUB_ENV
          echo "VERSION=$(echo $VERSION_LOCAL)" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo $VERSION_LOCAL)" >> $GITHUB_ENV
          echo "NAME_ID=$(echo $NAME_LOCAL)" >> $GITHUB_OUTPUT
          echo "NAME_ID=$(echo $NAME_LOCAL)" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo $BRANCH_LOCAL)" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$(echo $BRANCH_LOCAL)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(echo $REPOSITORY_NAME)" >> $GITHUB_OUTPUT
          echo "REPOSITORY_NAME=$(echo $REPOSITORY_NAME)" >> $GITHUB_ENV

          
      - name: Setting Java
      #  if: steps.check_approval.outputs.approved == 'true'
        run: |
          echo "JAVA_HOME=/opt/middleware/jvm/jdk1.8.0_211" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Check properties file on runner
      #  if: steps.check_approval.outputs.approved == 'true'
        run: |
          cd /opt/middleware/actions-runner/_work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/propiedades
          ls -la
          pwd

      - name: Finding last version of the artifact in Nexus
      #  if: steps.check_approval.outputs.approved == 'true'
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}  
          NEXUS_PASSWORD: ${{ secrets.NEXUS_TOKEN }}
          NEXUS_URL: ${{ secrets.NEXUS_URL_PRE }}
          NEXUS_REPOSITORY: ${{ secrets.NEXUS_REPOSITORY_PRE }}
          NEXUS_GROUP: ${{ env.REPOSITORY_NAME }}
        run: |
          response=$(curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD -s "$NEXUS_URL/service/rest/v1/search/assets?repository=$NEXUS_REPOSITORY&group=$NEXUS_GROUP" -H "accept: application/json")
          latest_version=$(echo $response | jq -r '.items | sort_by(.lastModified) | reverse | .[0].maven2.version')
          echo "La última versión del artefacto en Nexus es: $latest_version"
          version_corta=$(echo $latest_version | awk -F'-' '{print $1}')
          echo "La version corta es: $version_corta"
          
          # Descargar el artefacto con la ultima version
          mkdir -p "downloaded-artifacts-nexus"
          artifact_url="$NEXUS_URL/repository/$NEXUS_REPOSITORY/$NEXUS_GROUP/$NEXUS_GROUP-presentacion/$version_corta-SNAPSHOT/$NEXUS_GROUP-presentacion-$latest_version.war"
          echo "La url en nexus es: $artifact_url"
          filename=$(basename "$artifact_url")
          echo "El nombre del archivo es: $filename"
          curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD -o "downloaded-artifacts-nexus/$filename" "$artifact_url"
          pwd
          cd downloaded-artifacts-nexus
          pwd
          ls -la
          cp "$filename" "$NEXUS_GROUP-presentacion-$version_corta.war"
          ls -la

          echo "ARTIFACT-VERSION=$version_corta" >> $GITHUB_OUTPUT
          echo "ARTIFACT-VERSION=$version_corta" >> $GITHUB_ENV

          
### Inicia bloque para implementación de procesamiento de archivo properties

      - name: Check secret value
        id: check_secret
       # if: steps.check_approval.outputs.approved == 'true'
        run: |
           if [[ "${{ secrets.ARCHIVO_PROPERTIES_PRE }}" == "N" ]]; then
             echo "La variable tiene el valor de 'N'. Significa que No se realizará la copia del archivo. Continua el flujo hacia Preproduccion"
             echo "copia_archivo_properties=false" >> $GITHUB_OUTPUT
             echo "copia_archivo_properties=false" >> $GITHUB_ENV
           else
             echo "copia_archivo_properties=true" >> $GITHUB_OUTPUT
             echo "copia_archivo_properties=true" >> $GITHUB_ENV
           fi

      - name: Install sshpass
        run: |
          sudo yum install -y sshpass
        if: ${{ env.copia_archivo_properties == 'true' }}

      - name: Update ssh_config and restart SSH
        run: |
           cat /etc/ssh/ssh_config
           sudo sed -i 's/^.*RhostsRSAAuthentication.*$/# RhostsRSAAuthentication yes/' /etc/ssh/ssh_config
           sudo systemctl restart sshd
           cat /etc/ssh/ssh_config
        if: ${{ env.copia_archivo_properties == 'true' }}     

### Inicia bloque para implementacion de procesamiento de archivo properties, log4j2 y configuración de servidor
      - name: Set list of servers
        id: set_servers
        run: |
          echo "SERVER1=${{ secrets.AP_SERVER_PRE1 }}" >> $GITHUB_ENV
          echo "SERVER2=${{ secrets.AP_SERVER_PRE2 }}" >> $GITHUB_ENV
          echo "server_password=${{ secrets.AP_PASSWORD_PRE }}" >> $GITHUB_ENV
          echo "server_user=${{ secrets.AP_USERNAME_PRE }}" >> $GITHUB_ENV
          echo "server_ruta=${{ secrets.AP_RUTA_PRE }}" >> $GITHUB_ENV

      - name: Copy files and execute commands on multiple servers
        run: |
          # Obtener la lista de servidores desde GITHUB_ENV
          servers=($SERVER1 $SERVER2)  # Lista de servidores

          # Iterar sobre la lista de servidores con un bucle for
          for server_address in "${servers[@]}"; do
            echo "Procesando servidor: $server_address"

            # Copiar archivo properties
            server_result=$(sshpass -p $server_password ssh $server_user@$server_address '[ -f $server_ruta/${{ env.REPOSITORY_NAME }}.properties ] && echo "SI" || echo "NO"')
            echo "Resultado_${server}: $server_result"
            
            sshpass -p $server_password scp /opt/middleware/actions-runner/_work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/propiedades/${{ env.REPOSITORY_NAME }}.properties $server_user@$server_address:$server_ruta
            echo "Archivo properties actualizado exitosamente en $server_address"
            
            # Copiar log4j2.xml
            server_result_log4j=$(sshpass -p $server_password ssh $server_user@$server_address '[ -f $server_ruta/log4j2/${{ env.REPOSITORY_NAME }}-log4j2.xml ] && echo "SI" || echo "NO"')
            echo "Resultado_${server}_log4j: $server_result_log4j"
            
            sshpass -p $server_password scp /opt/middleware/actions-runner/_work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/propiedades/log4j2/${{ env.REPOSITORY_NAME }}-log4j2.xml $server_user@$server_address:$server_ruta/log4j2
            echo "Archivo log4j2.xml actualizado exitosamente en $server"

            # Ejecutar el script de configuración en el servidor
            OUTPUT=$(sshpass -p $server_password ssh -o StrictHostKeyChecking=no $server_user@$server_address '
              echo "Directorio actual:"; pwd;
              echo "Variables de entorno:"; env;
              echo "Ejecutando el script:"; bash ${{ secrets.WEBLOGIC_RUTA_SET_PRE }}/setWLSEnv.sh 2>&1
            ')
            echo "$OUTPUT"
          done
        if: ${{ env.copia_archivo_properties == 'true' }} 

### Termina bloque para implementacion de procesamiento de archivo properties, log4j2 y configuración del servidor
      
      - name: Check Artifact exists
       # if: steps.check_approval.outputs.approved == 'true'
        id: artifact-version
        run: |
          set -x
          salida=$(java -cp "/opt/middleware/oracle/wls12214/wlserver/server/lib/weblogic.jar" weblogic.Deployer \
          -adminurl ${{ secrets.WEBLOGIC_HOST_PRE }} \
          -username ${{ secrets.WEBLOGIC_USERNAME_PRE }} \
          -password ${{ secrets.WEBLOGIC_PASSWORD_PRE }} \
          -listapps | grep "${{ env.REPOSITORY_NAME }}-presentacion" | sed 's/^$/0/' )

          echo "OUTPUT=$salida" >> $GITHUB_OUTPUT
          echo "OUTPUT=$salida" >> $GITHUB_ENV
          echo "EXIT_CODE=${?}" >> $GITHUB_OUTPUT
          echo "EXIT_CODE=${?}" >> $GITHUB_ENV

      - name: Check exit code, deploy
        id: check-exit
      #  if: steps.check_approval.outputs.approved == 'true'
        run: |
            if [[ "${{ env.EXIT_CODE }}" -eq 0 && -z "${{ env.OUTPUT }}" ]]; then
            # este codigo es cuando el artefacto no existe en weblogic, primera vez que se despliega al ambiente Weblogic Preproduccion
              echo "Command executed successfully"
              echo "La aplicación no se encontró, se realiza primer deploy a Weblogic Preproduccion .. "
              java -cp /opt/middleware/oracle/wls12214/wlserver/server/lib/weblogic.jar weblogic.Deployer \
              -adminurl ${{ secrets.WEBLOGIC_HOST_PRE }} \
              -username ${{ secrets.WEBLOGIC_USERNAME_PRE }} \
              -password ${{ secrets.WEBLOGIC_PASSWORD_PRE }} \
              -deploy -name ${{ env.REPOSITORY_NAME }}-presentacion-${{ env.ARTIFACT-VERSION }}  -remote \
              -targets ${{ secrets.WEBLOGIC_CLUSTER_PRE }} \
              -source /opt/middleware/actions-runner/_work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/downloaded-artifacts-nexus/${{ env.REPOSITORY_NAME }}-presentacion-${{ env.ARTIFACT-VERSION }}.war -upload \
              
              echo "no-ejecutar-siguientes-pasos=true" >> $GITHUB_OUTPUT
              echo "no-ejecutar-siguientes-pasos=true" >> $GITHUB_ENV
              echo "Proceso terminado- Primer Deploy con exito a Weblogic Preproduccion del proyecto ${{ env.REPOSITORY_NAME }}"
                 
            else
              # este codigo es cuando el artefacto si existe, pero hay que validar si tiene o no version incluida en el nombre
              echo "Command failed with exit code ${{ env.EXIT_CODE }}"
              if [[ ! -z "${{ env.OUTPUT }}" ]]; then
                salida=$(java -cp "/opt/middleware/oracle/wls12214/wlserver/server/lib/weblogic.jar" weblogic.Deployer \
                -adminurl ${{ secrets.WEBLOGIC_HOST_PRE }} \
                -username ${{ secrets.WEBLOGIC_USERNAME_PRE }} \
                -password ${{ secrets.WEBLOGIC_PASSWORD_PRE }} \
                -listapps | grep "${{ env.REPOSITORY_NAME }}-presentacion*" )
                
                echo "Artifact-name: $salida"
                echo "artifact-name=$(echo $salida)" >> $GITHUB_OUTPUT
                echo "artifact-name=$(echo $salida)" >> $GITHUB_ENV
                versionado=$(echo "$salida" | gawk -F'-' '{print $NF}')
                echo "versionado: $versionado"

                if [ "$versionado" = "" ]; then
                  echo "Significa que no hay version, desplegarse el mismo objeto"
                  
                  java -cp /opt/middleware/oracle/wls12214/wlserver/server/lib/weblogic.jar weblogic.Deployer \
                  -adminurl ${{ secrets.WEBLOGIC_HOST_PRE }} \
                  -username ${{ secrets.WEBLOGIC_USERNAME_PRE }} \
                  -password ${{ secrets.WEBLOGIC_PASSWORD_PRE }} \
                  -undeploy -name ${{ env.REPOSITORY_NAME }}-presentacion-  -remote \
                  -targets ${{ secrets.WEBLOGIC_CLUSTER_PRE }}                  
    
                  echo "Esperando a que se complete el undeploy del artefacto..."
                  sleep 15
                  echo "Iniciando el deploy"
                 
                  java -cp /opt/middleware/oracle/wls12214/wlserver/server/lib/weblogic.jar weblogic.Deployer \
                  -adminurl ${{ secrets.WEBLOGIC_HOST_PRE }} \
                  -username ${{ secrets.WEBLOGIC_USERNAME_PRE }} \
                  -password ${{ secrets.WEBLOGIC_PASSWORD_PRE }} \
                  -deploy -name ${{ env.REPOSITORY_NAME }}-presentacion-${{ env.ARTIFACT-VERSION }}  -remote \
                  -targets ${{ secrets.WEBLOGIC_CLUSTER_PRE }} \
                  -source /opt/middleware/actions-runner/_work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/downloaded-artifacts-nexus/${{ env.REPOSITORY_NAME }}-presentacion-${{ env.ARTIFACT-VERSION }}.war -upload \
                  
                   echo "no-ejecutar-siguientes-pasos=true" >> $GITHUB_OUTPUT
                   echo "no-ejecutar-siguientes-pasos=true" >> $GITHUB_ENV
                   echo "Proceso terminado- Deploy con exito Weblogic Preproduccion- version ${{ env.ARTIFACT-VERSION }}"
                  
                else
                
                   echo "Significa que si existe el objeto pero hay que reemplazarlo pues trae nueva version"
                   salida=$(java -cp "/opt/middleware/oracle/wls12214/wlserver/server/lib/weblogic.jar" weblogic.Deployer \
                     -adminurl ${{ secrets.WEBLOGIC_HOST_PRE }} \
                     -username ${{ secrets.WEBLOGIC_USERNAME_PRE }} \
                     -password ${{ secrets.WEBLOGIC_PASSWORD_PRE }} \
                     -listapps | grep "${{ env.REPOSITORY_NAME }}-presentacion*" )
                   echo "Artifact-name: $salida"
                   versionado=$(echo "$salida" | gawk -F'-' '{print $NF}')
                   echo "versionado: $versionado"
                   echo "version-deployada=$versionado" >> $GITHUB_ENV
                   echo "no-ejecutar-siguientes-pasos=false" >> $GITHUB_OUTPUT
                   echo "no-ejecutar-siguientes-pasos=false" >> $GITHUB_ENV
                  
                 fi
               fi
             fi 
        
      - name: Undeploy weblogic, deploy
        run: |
            java -cp /opt/middleware/oracle/wls12214/wlserver/server/lib/weblogic.jar weblogic.Deployer \
              -adminurl ${{ secrets.WEBLOGIC_HOST_PRE }} \
              -username ${{ secrets.WEBLOGIC_USERNAME_PRE }} \
              -password ${{ secrets.WEBLOGIC_PASSWORD_PRE }} \
              -undeploy -name ${{ env.REPOSITORY_NAME }}-presentacion-${{ env.version-deployada }}  -remote \
              -targets ${{ secrets.WEBLOGIC_CLUSTER_PRE }}              
  
            echo "Esperando a que se complete el undeploy del artefacto..."
            sleep 15
            echo "Iniciando el deploy"
            echo "nuevaVersion: ${{ env.ARTIFACT-VERSION }}"
  
            java -cp /opt/middleware/oracle/wls12214/wlserver/server/lib/weblogic.jar weblogic.Deployer \
              -adminurl ${{ secrets.WEBLOGIC_HOST_PRE }} \
              -username ${{ secrets.WEBLOGIC_USERNAME_PRE }} \
              -password ${{ secrets.WEBLOGIC_PASSWORD_PRE }} \
              -deploy -name ${{ env.REPOSITORY_NAME }}-presentacion-${{ env.ARTIFACT-VERSION }}  -remote \
              -targets ${{ secrets.WEBLOGIC_CLUSTER_PRE }} \
              -source /opt/middleware/actions-runner/_work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/downloaded-artifacts-nexus/${{ env.REPOSITORY_NAME }}-presentacion-${{ env.ARTIFACT-VERSION }}.war -upload \
              
            echo "Proceso terminado- Deploy con exito Weblogic Preproduccion"      
        if: ${{ env.no-ejecutar-siguientes-pasos == 'false' }}

### Finalmente se sube el artefacto a Nexus Releases para disponer del mismo para el despliegue a Produccion

      - name: Carga artefacto Nexus Releases
        run: |
           echo "Inicia carga de artefacto a Nexus - Releases" 
              repo_full_name="${{ github.repository }}"
              repo_name=$(echo "$repo_full_name" | cut -d '/' -f 2)
              ruta_target="/opt/middleware/actions-runner/_work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/downloaded-artifacts-nexus/"
              cd $ruta_target
              ls -la
              mvn deploy:deploy-file \
                -Dfile=${{ env.REPOSITORY_NAME }}-presentacion-${{ env.ARTIFACT-VERSION }}.war \
                -DrepositoryId=releases \
                -Durl=https://nexus.procesar.com.mx/nexus/repository/maven-releases/ \
                -DgroupId=${{ env.REPOSITORY_NAME }} \
                -DartifactId=${{ env.REPOSITORY_NAME }}-presentacion \
                -Dversion=${{ env.ARTIFACT-VERSION }} \
                -Dpackaging=war \
                -DrepositoryUsername=${{ secrets.NEXUS_USERNAME }} \
                -DrepositoryPassword=${{ secrets.NEXUS_TOKEN }} \
                -s ~/.m2/repository/settings.xml

            echo "Proceso completo con exito Weblogic Preproduccion"   
